# Config for 'dist'
[dist]
# The preferred dist version to use in CI
cargo-dist-version = "0.19.1"
# CI backends to support
ci = ["github"]
# The installers to generate for each release
installers = ["shell", "powershell"]
# The archive format to use for non-windows builds
unix-archive = ".tar.gz"
# Target platforms to build binaries for
targets = ["x86_64-unknown-linux-gnu", "aarch64-apple-darwin", "x86_64-pc-windows-msvc"]
# Whether to publish prereleases to GitHub Releases
prerelease-to-github = true
