name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
  workflow_dispatch:

jobs:
  # Plan the release
  plan:
    runs-on: ubuntu-latest
    outputs:
      val: ${{ steps.plan.outputs.manifest }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install dist
        run: curl --proto '=https' --tlsv1.2 -LsSf https://github.com/axodotdev/cargo-dist/releases/download/v0.19.1/cargo-dist-installer.sh | sh
      - id: plan
        run: |
          dist plan --tag=${{ github.ref_name }} --output-format=json > dist-manifest.json
          echo "manifest=$(cat dist-manifest.json | jq -c .)" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Build and Upload Artifacts
  upload-artifacts:
    needs: plan
    strategy:
      matrix:
        include: ${{ fromJson(needs.plan.outputs.val).artifacts_matrix }}
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install dist
        run: ${{ matrix.install_dist }}
      - name: Build artifacts
        run: dist build --tag=${{ github.ref_name }} --output-format=json ${{ matrix.dist_args }} > dist-manifest.json
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-${{ matrix.runner }}
          path: target/distrib/*

  # Create the GitHub Release
  publish-release:
    needs: [plan, upload-artifacts]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dist
        run: curl --proto '=https' --tlsv1.2 -LsSf https://github.com/axodotdev/cargo-dist/releases/download/v0.19.1/cargo-dist-installer.sh | sh
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: target/distrib/
          pattern: artifacts-*
          merge-multiple: true
      - name: Publish Release
        run: dist host --steps=upload --tag=${{ github.ref_name }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
